version: '3.9'

services:
  portfolio: # Nombre del contenedor
    build:
      context: .. # Ubicación del dockerfile
      dockerfile: .docker/dev.Dockerfile # Nombre del dockerfile
    command: bash -c 'pnpm i && pnpm build'
    volumes:
      - ../.:/app # Volumen del proyecto montado en /app
      - nodemodules:/app/node_modules # Volumen del node_modules montado en /app/node_modules
      - pnpmstore:/app/.pnpm-store # Volumen del pnpm-store  montado en /app/.pnpm-store
    ports:
      - 5173:5173 # Puerto local : Puerto del contenedor
      - 9229:9229
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  nodemodules:
  pnpmstore:
